---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "30 1 * * 3"

defaults:
  run:
    working-directory: 'goathy.technitium_dns'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          path: 'goathy.technitium_dns'

      - name: Run ansible-lint
        uses: ansible/ansible-lint@8ba9595a4acd1b906eb75568b34f6ef592cd1528
        with:
          setup_python: "true"
          python_version: "3.13"
          working_directory: 'goathy.technitium_dns'

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - almalinux9
          - almalinux10

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          path: 'goathy.technitium_dns'

      - name: Set up Python 3.
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.13'  # Can't go to 3.14+ until Ansible 13.x

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
